name: Deploy to AWS
'on':
  workflow_dispatch: {}
env:
  CI: 1

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: npx ampx pipeline-deploy --branch ${{ github.event.repository.default_branch }} --app-id ${{ secrets.AMPLIFY_APP_ID }}