name: Deploy to AWS
'on':
  workflow_dispatch: {}
env:
  CI: 1

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/google-auth-deployer
          aws-region: eu-central-1
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: npx ampx pipeline-deploy --branch ${{ github.event.repository.default_branch }} --app-id ${{ secrets.AMPLIFY_APP_ID }}